# Generated by Django 2.2.6 on 2019-10-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191002_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensalista',
            name='veiculo',
        ),
        migrations.RemoveField(
            model_name='movmensalista',
            name='mensalista',
        ),
        migrations.RemoveField(
            model_name='movrotativo',
            name='veiculo',
        ),
        migrations.DeleteModel(
            name='Parametros',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='proprietario',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='user',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Mensalista',
        ),
        migrations.DeleteModel(
            name='MovMensalista',
        ),
        migrations.DeleteModel(
            name='MovRotativo',
        ),
        migrations.DeleteModel(
            name='Veiculo',
        ),
    ]
