# Generated by Django 2.2.6 on 2019-10-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191002_1351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
