# Generated by Django 2.2.6 on 2019-10-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aluno_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(choices=[('1', 'cuidador'), ('2', 'injetaveis'), ('3', 'sondas')], max_length=1),
        ),
    ]
