# Generated by Django 2.2.6 on 2019-10-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aluno_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('cpf', models.CharField(blank=True, max_length=20)),
                ('coren', models.CharField(blank=True, max_length=20)),
                ('pai', models.CharField(blank=True, max_length=20)),
                ('mae', models.CharField(blank=True, max_length=20)),
                ('nascimento', models.DateField(blank=True)),
            ],
        ),
    ]
