# Generated by Django 2.2.6 on 2019-10-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='codigo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='investimento',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='manha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='noite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='outroHorario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='tarde',
            field=models.BooleanField(default=False),
        ),
    ]
