# Generated by Django 2.2.6 on 2019-10-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191024_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='facilitador',
            field=models.ManyToManyField(to='core.Professor'),
        ),
        migrations.AddField(
            model_name='curso',
            name='obs',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
