# Generated by Django 2.2.6 on 2019-10-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191024_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
