# Generated by Django 2.2.6 on 2019-10-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_curso_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
